apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-comment-deployment
  labels:
    apps: kube-comment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-comment
  template:
    metadata:
      labels:
        app: kube-comment
    spec:
      containers:
      - name: kube-comment-container
        image: irvanzarkasie/xendit-comment:v1.0
        ports:
        - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-logger-deployment
  labels:
    apps: kube-logger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-logger
  template:
    metadata:
      labels:
        app: kube-logger
    spec:
      containers:
      - name: kube-logger-container
        image: irvanzarkasie/xendit-logger:v1.0
        ports:
        - containerPort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-db-deployment
  labels:
    apps: kube-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-db
  template:
    metadata:
      labels:
        app: kube-db
    spec:
      containers:
      - name: kube-db-container
        image: irvanzarkasie/xendit-db:v1.0
        ports:
        - containerPort: 3002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    apps: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb-container
        image: mongo:3.4.22-xenial
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: kube-comment
  labels:
    app: kube-comment
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000
    protocol: TCP
  selector:
    app: kube-comment
---
apiVersion: v1
kind: Service
metadata:
  name: kube-logger
  labels:
    app: kube-logger
spec:
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
  selector:
    app: kube-logger
---
apiVersion: v1
kind: Service
metadata:
  name: kube-db
  labels:
    app: kube-db
spec:
  ports:
  - port: 3002
    targetPort: 3002
    protocol: TCP
  selector:
    app: kube-db
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
  selector:
    app: mongodb
